packages:
  - examples/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^25.8.0
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  knip: ^6.14.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  "@clerk/shared": true
  esbuild: true
  sharp: true
  vue-demi: true
  workerd: true
